### ISSUE TITLE
Add support for .ipynb files

### ISSUE THREAD

**Issue by Haptikal** [iCrawl/discord-vscode#802]
Currently it just says idling when working on a document of this type

**Comment by Zenoix** [comment]
I really want this as well but it seems to work before vscode actually renders the cells so it might just be a bug

**Comment by iiLeafy** [comment]
shouldn't this be in pull requests [well atleast if you can add like 2 lines of code] and provide a picture.

**Comment by JosephDn** [comment]
I also really want this, shame it is still yet to be fixed.

**Comment by anoushk1234** [comment]
I want this too, I stopped using this extension for this reason only

**Comment by SwiftWinds** [comment]
> I want this too, I stopped using this extension for this reason only

Did you find a better alternative or something?

**Comment by anoushk1234** [comment]
> 
> 
> > I want this too, I stopped using this extension for this reason only
> 
> Did you find a better alternative or something?

Yes but it kinda works, at least it doesn't show idling
link:https://marketplace.visualstudio.com/items?itemName=satoqz.yet-another-discord-presence

**Comment by renzodamgo** [comment]
> shouldn't this be in pull requests [well atleast if you can add like 2 lines of code] and provide a picture.
#1030 There is one but I don't know if this will resolve the issue

**Comment by renzodamgo** [comment]
#1030

**Comment by Nikhil0504** [comment]
> > shouldn't this be in pull requests [well atleast if you can add like 2 lines of code] and provide a picture.
> 
> #1030 There is one but I don't know if this will resolve the issue
We can try it and see

**Comment by Awosk** [comment]
It works fine in VS Code insiders version, but not in VS Code . there must be a mistake

**Comment by iCrawl** [comment]
That should be fixed in v5.7.0

**Comment by adiwahyudi** [comment]
mine in v5.7.0 still not fixed,anybody else ?

**Comment by that-mint** [comment]
> mine in v5.7.0 still not fixed,anybody else ?
Yep, currently in on 5.7.0 on Windows, it doesn't seem to recognize .ipynb files.

**Comment by PrincelyKitilya** [comment]
Also in here and still having the same issues has anyone found a way to fix it
